### ISSUE TITLE
Document adding new interactables

### ISSUE THREAD

**Issue by LordMonoxide** [Legend-of-Dragoon-Modding/Modding-Ideas-and-Discussion#115]
- Link to flags documentation
- Need to talk about flag collisions with other mods, note we'll solve this in the future
- Interaction position, size, ...

**Comment by avionanx** [comment]
Closed with [Interactable Tutorial](https://docs.google.com/document/d/1x6LuZPD1rfgsasVGbm0zGnPZk6SjK_AnSDoxGlCKCI0/edit). May update formatting and/or information depending on if we find anything new about it.
